In [78]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [79]:
df = pd.read_csv('quikr_car.csv')

In [80]:
df.head()

,name,company,year,Price,kms_driven,fuel_type
0,Hyundai Santro Xing XO eRLX Euro III,Hyundai,2007,"80,000","45,000 kms",Petrol
1,Mahindra Jeep CL550 MDI,Mahindra,2006,"4,25,000",40 kms,Diesel
2,Maruti Suzuki Alto 800 Vxi,Maruti,2018,Ask For Price,"22,000 kms",Petrol
3,Hyundai Grand i10 Magna 1.2 Kappa VTVT,Hyundai,2014,"3,25,000","28,000 kms",Petrol
4,Ford EcoSport Titanium 1.5L TDCi,Ford,2014,"5,75,000","36,000 kms",Diesel

In [81]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 892 entries, 0 to 891
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        892 non-null    str
 1   company     892 non-null    str
 2   year        892 non-null    str
 3   Price       892 non-null    str
 4   kms_driven  840 non-null    str
 5   fuel_type   837 non-null    str
dtypes: str(6)
memory usage: 92.3 KB

In [82]:
df.isnull().sum()

name           0
company        0
year           0
Price          0
kms_driven    52
fuel_type     55
dtype: int64

# EDA

In [83]:
df['year'].unique()
# a lots of trash values in year column. We need to clean it up before we can use it for any analysis or modeling.
# need to change the data type of year column to int and then we can use it for analysis and modeling.

<ArrowStringArray>
['2007', '2006', '2018', '2014', '2015', '2012', '2013', '2016', '2010',
 '2017', '2008', '2011', '2019', '2009', '2005', '2000',  '...', '150k',
 'TOUR', '2003', 'r 15', '2004', 'Zest', '/-Rs', 'sale', '1995', 'ara)',
 '2002', 'SELL', '2001', 'tion', 'odel', '2 bs', 'arry',  'Eon', 'o...',
 'ture',  'emi',  'car', 'able',  'no.', 'd...', 'SALE', 'digo', 'sell',
 'd Ex', 'n...', 'e...', 'D...', ', Ac', 'go .', 'k...', 'o c4', 'zire',
 'cent', 'Sumo',  'cab', 't xe',  'EV2', 'r...', 'zest']
Length: 61, dtype: str

In [84]:
df['Price'].unique()
# some trash values in price column. We need to clean it up before we can use it for any analysis or modeling.
# need to change the data type of price column to int and then we can use it for analysis and modeling.

<ArrowStringArray>
[       '80,000',      '4,25,000', 'Ask For Price',      '3,25,000',
      '5,75,000',      '1,75,000',      '1,90,000',      '8,30,000',
      '2,50,000',      '1,82,000',
 ...
        '42,000',      '1,89,000',      '1,62,000',        '35,999',
     '29,00,000',        '39,999',        '50,500',      '5,10,000',
      '8,60,000',      '5,00,001']
Length: 274, dtype: str

In [85]:
df['kms_driven'].unique()
# some data is missing 
# some trash values
# channge the data type

<ArrowStringArray>
[  '45,000 kms',       '40 kms',   '22,000 kms',   '28,000 kms',
   '36,000 kms',   '59,000 kms',   '41,000 kms',   '25,000 kms',
   '24,530 kms',   '60,000 kms',
 ...
   '60,123 kms',   '38,900 kms', '1,37,495 kms',   '91,200 kms',
 '1,46,000 kms', '1,00,800 kms',    '2,100 kms',    '2,500 kms',
 '1,32,000 kms',       'Petrol']
Length: 259, dtype: str

In [86]:
df['fuel_type'].unique()
# some data is missing

<ArrowStringArray>
['Petrol', 'Diesel', nan, 'LPG']
Length: 4, dtype: str

In [87]:
df['name'].unique()
# every car has a unique name
# so  i select the first 3 words of the name column and create a new column called brand which will be used for analysis and modeling.

<ArrowStringArray>
[  'Hyundai Santro Xing XO eRLX Euro III',
                'Mahindra Jeep CL550 MDI',
             'Maruti Suzuki Alto 800 Vxi',
 'Hyundai Grand i10 Magna 1.2 Kappa VTVT',
       'Ford EcoSport Titanium 1.5L TDCi',
                              'Ford Figo',
                            'Hyundai Eon',
       'Ford EcoSport Ambiente 1.5L TDCi',
         'Maruti Suzuki Alto K10 VXi AMT',
            'Skoda Fabia Classic 1.2 MPI',
 ...
         'Mercedes Benz C Class 200 K MT',
                            'Skoda Fabia',
  'Maruti Suzuki Alto 800 Select Variant',
             'Maruti Suzuki Ritz VXI ABS',
                       'tata zest 2017 f',
              'Tata Indica V2 DLE BS III',
                                     'Ta',
                    'Tata Zest XM Diesel',
               'Honda Amaze 1.2 E i VTEC',
              'Chevrolet Sail 1.2 LT ABS']
Length: 525, dtype: str

In [88]:
df['company'].unique()

<ArrowStringArray>
[   'Hyundai',   'Mahindra',     'Maruti',       'Ford',      'Skoda',
       'Audi',     'Toyota',    'Renault',      'Honda',     'Datsun',
 'Mitsubishi',       'Tata', 'Volkswagen',          'I',  'Chevrolet',
       'Mini',        'BMW',     'Nissan',  'Hindustan',       'Fiat',
 'Commercial',     'MARUTI',      'Force',   'Mercedes',       'Land',
     'Yamaha',    'selling',     'URJENT',      'Swift',       'Used',
     'Jaguar',       'Jeep',       'tata',       'Sale',       'very',
      'Volvo',          'i',       '2012',       'Well',        'all',
          '7',          '9',    'scratch',     'urgent',       'sell',
       'TATA',        'Any',       'Tara']
Length: 48, dtype: str

In [89]:
# backup the original dataframe
dff = df.copy()

# cleaning

In [90]:
dff.head()

,name,company,year,Price,kms_driven,fuel_type
0,Hyundai Santro Xing XO eRLX Euro III,Hyundai,2007,"80,000","45,000 kms",Petrol
1,Mahindra Jeep CL550 MDI,Mahindra,2006,"4,25,000",40 kms,Diesel
2,Maruti Suzuki Alto 800 Vxi,Maruti,2018,Ask For Price,"22,000 kms",Petrol
3,Hyundai Grand i10 Magna 1.2 Kappa VTVT,Hyundai,2014,"3,25,000","28,000 kms",Petrol
4,Ford EcoSport Titanium 1.5L TDCi,Ford,2014,"5,75,000","36,000 kms",Diesel

In [91]:
dff['company'].unique()

<ArrowStringArray>
[   'Hyundai',   'Mahindra',     'Maruti',       'Ford',      'Skoda',
       'Audi',     'Toyota',    'Renault',      'Honda',     'Datsun',
 'Mitsubishi',       'Tata', 'Volkswagen',          'I',  'Chevrolet',
       'Mini',        'BMW',     'Nissan',  'Hindustan',       'Fiat',
 'Commercial',     'MARUTI',      'Force',   'Mercedes',       'Land',
     'Yamaha',    'selling',     'URJENT',      'Swift',       'Used',
     'Jaguar',       'Jeep',       'tata',       'Sale',       'very',
      'Volvo',          'i',       '2012',       'Well',        'all',
          '7',          '9',    'scratch',     'urgent',       'sell',
       'TATA',        'Any',       'Tara']
Length: 48, dtype: str

In [92]:
dff=dff[dff['year'].str.isnumeric()]
dff.shape

(842, 6)

In [93]:
dff['year']=dff['year'].astype(int)

In [94]:
dff = dff[dff['Price'] != 'Ask For Price']
dff['Price'] = dff['Price'].str.replace(',', '').astype(int)
dff['Price']

0       80000
1      425000
3      325000
4      575000
6      175000
        ...
886    300000
888    260000
889    390000
890    180000
891    160000
Name: Price, Length: 819, dtype: int64

In [95]:
dff = dff[dff['kms_driven'] != 'Petrol']
dff['kms_driven'] = dff['kms_driven'].str.replace(' kms', '').str.replace(',', '').astype(int)
dff['kms_driven']

0       45000
1          40
3       28000
4       36000
6       41000
        ...
883     50000
885     30000
886    132000
888     27000
889     40000
Name: kms_driven, Length: 817, dtype: int64

In [96]:
dff['fuel_type'].unique()

<ArrowStringArray>
['Petrol', 'Diesel', nan, 'LPG']
Length: 4, dtype: str

In [97]:
dff = dff[~dff['fuel_type'].isna()]
dff['fuel_type'].unique()

<ArrowStringArray>
['Petrol', 'Diesel', 'LPG']
Length: 3, dtype: str

In [98]:
dff.info()

<class 'pandas.DataFrame'>
Index: 816 entries, 0 to 889
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        816 non-null    str
 1   company     816 non-null    str
 2   year        816 non-null    int64
 3   Price       816 non-null    int64
 4   kms_driven  816 non-null    int64
 5   fuel_type   816 non-null    str
dtypes: int64(3), str(3)
memory usage: 74.1 KB

In [99]:
dff['name'] = dff['name'].str.split(' ').str.slice(0, 3).str.join(' ')
dff

                       name   company  year   Price  kms_driven fuel_type
0       Hyundai Santro Xing   Hyundai  2007   80000       45000    Petrol
1       Mahindra Jeep CL550  Mahindra  2006  425000          40    Diesel
3         Hyundai Grand i10   Hyundai  2014  325000       28000    Petrol
4    Ford EcoSport Titanium      Ford  2014  575000       36000    Diesel
6                 Ford Figo      Ford  2012  175000       41000    Diesel
..                      ...       ...   ...     ...         ...       ...
883      Maruti Suzuki Ritz    Maruti  2011  270000       50000    Petrol
885          Tata Indica V2      Tata  2009  110000       30000    Diesel
886    Toyota Corolla Altis    Toyota  2009  300000      132000    Petrol
888            Tata Zest XM      Tata  2018  260000       27000    Diesel
889      Mahindra Quanto C8  Mahindra  2013  390000       40000    Diesel

[816 rows x 6 columns]

In [100]:
dff.reset_index(drop=True , inplace=True)

In [101]:
dff

                       name   company  year   Price  kms_driven fuel_type
0       Hyundai Santro Xing   Hyundai  2007   80000       45000    Petrol
1       Mahindra Jeep CL550  Mahindra  2006  425000          40    Diesel
2         Hyundai Grand i10   Hyundai  2014  325000       28000    Petrol
3    Ford EcoSport Titanium      Ford  2014  575000       36000    Diesel
4                 Ford Figo      Ford  2012  175000       41000    Diesel
..                      ...       ...   ...     ...         ...       ...
811      Maruti Suzuki Ritz    Maruti  2011  270000       50000    Petrol
812          Tata Indica V2      Tata  2009  110000       30000    Diesel
813    Toyota Corolla Altis    Toyota  2009  300000      132000    Petrol
814            Tata Zest XM      Tata  2018  260000       27000    Diesel
815      Mahindra Quanto C8  Mahindra  2013  390000       40000    Diesel

[816 rows x 6 columns]

In [102]:
dff.describe()
# there is one outlier in the price column

              year         Price     kms_driven
count   816.000000  8.160000e+02     816.000000
mean   2012.444853  4.117176e+05   46275.531863
std       4.002992  4.751844e+05   34297.428044
min    1995.000000  3.000000e+04       0.000000
25%    2010.000000  1.750000e+05   27000.000000
50%    2013.000000  2.999990e+05   41000.000000
75%    2015.000000  4.912500e+05   56818.500000
max    2019.000000  8.500003e+06  400000.000000

In [103]:
dff[dff['Price']>6e6]   ## so we need to remove this outlier before we can use it for analysis and modeling.
dff = dff[dff['Price']<6e6].reset_index(drop=True)
dff.describe()

              year         Price     kms_driven
count   815.000000  8.150000e+02     815.000000
mean   2012.442945  4.017933e+05   46277.096933
std       4.005079  3.815888e+05   34318.459638
min    1995.000000  3.000000e+04       0.000000
25%    2010.000000  1.750000e+05   27000.000000
50%    2013.000000  2.999990e+05   41000.000000
75%    2015.000000  4.900000e+05   56879.000000
max    2019.000000  3.100000e+06  400000.000000

In [104]:
dff['Price'].sort_values(ascending=False)

677    3100000
770    2900000
485    2800000
626    2390000
625    2190000
        ...
526      35000
430      32000
567      32000
372      30000
781      30000
Name: Price, Length: 815, dtype: int64

In [105]:
dff

                       name   company  year   Price  kms_driven fuel_type
0       Hyundai Santro Xing   Hyundai  2007   80000       45000    Petrol
1       Mahindra Jeep CL550  Mahindra  2006  425000          40    Diesel
2         Hyundai Grand i10   Hyundai  2014  325000       28000    Petrol
3    Ford EcoSport Titanium      Ford  2014  575000       36000    Diesel
4                 Ford Figo      Ford  2012  175000       41000    Diesel
..                      ...       ...   ...     ...         ...       ...
810      Maruti Suzuki Ritz    Maruti  2011  270000       50000    Petrol
811          Tata Indica V2      Tata  2009  110000       30000    Diesel
812    Toyota Corolla Altis    Toyota  2009  300000      132000    Petrol
813            Tata Zest XM      Tata  2018  260000       27000    Diesel
814      Mahindra Quanto C8  Mahindra  2013  390000       40000    Diesel

[815 rows x 6 columns]

In [106]:
dff.to_csv('Cleaned car.csv', index=False)

In [107]:
dff.columns

Index(['name', 'company', 'year', 'Price', 'kms_driven', 'fuel_type'], dtype='str')

# Model

In [108]:
car = pd.read_csv('Cleaned car.csv')
car

                       name   company  year   Price  kms_driven fuel_type
0       Hyundai Santro Xing   Hyundai  2007   80000       45000    Petrol
1       Mahindra Jeep CL550  Mahindra  2006  425000          40    Diesel
2         Hyundai Grand i10   Hyundai  2014  325000       28000    Petrol
3    Ford EcoSport Titanium      Ford  2014  575000       36000    Diesel
4                 Ford Figo      Ford  2012  175000       41000    Diesel
..                      ...       ...   ...     ...         ...       ...
810      Maruti Suzuki Ritz    Maruti  2011  270000       50000    Petrol
811          Tata Indica V2      Tata  2009  110000       30000    Diesel
812    Toyota Corolla Altis    Toyota  2009  300000      132000    Petrol
813            Tata Zest XM      Tata  2018  260000       27000    Diesel
814      Mahindra Quanto C8  Mahindra  2013  390000       40000    Diesel

[815 rows x 6 columns]

In [109]:
car.columns

Index(['name', 'company', 'year', 'Price', 'kms_driven', 'fuel_type'], dtype='str')

In [110]:
p = car.drop('company' , axis=1)
p.columns

Index(['name', 'year', 'Price', 'kms_driven', 'fuel_type'], dtype='str')

In [111]:
x = p.drop('Price', axis=1)

y = car['Price']

In [112]:
x

                       name  year  kms_driven fuel_type
0       Hyundai Santro Xing  2007       45000    Petrol
1       Mahindra Jeep CL550  2006          40    Diesel
2         Hyundai Grand i10  2014       28000    Petrol
3    Ford EcoSport Titanium  2014       36000    Diesel
4                 Ford Figo  2012       41000    Diesel
..                      ...   ...         ...       ...
810      Maruti Suzuki Ritz  2011       50000    Petrol
811          Tata Indica V2  2009       30000    Diesel
812    Toyota Corolla Altis  2009      132000    Petrol
813            Tata Zest XM  2018       27000    Diesel
814      Mahindra Quanto C8  2013       40000    Diesel

[815 rows x 4 columns]

In [113]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2, random_state=42)

In [114]:
from  sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score , accuracy_score
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import  make_column_transformer
from sklearn.pipeline import make_pipeline
from sklearn.ensemble import RandomForestRegressor

In [115]:
ohe = OneHotEncoder()
ohe.fit(x[['name', 'fuel_type']])

OneHotEncoder()

In [120]:


colmn_trans = make_column_transformer(
    (OneHotEncoder(categories=ohe.categories_), ['name',  'fuel_type']),
    remainder='passthrough'
)

In [121]:
lr = LinearRegression()
rnf = RandomForestRegressor()

In [122]:
pipe1 = make_pipeline(colmn_trans, lr)
pipe2 = make_pipeline(colmn_trans, rnf)

In [123]:
pipe1.fit(x_train, y_train)
pipe2.fit(x_train, y_train)

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('onehotencoder',
                                                  OneHotEncoder(categories=[array(['Audi A3 Cabriolet', 'Audi A4 1.8', 'Audi A4 2.0', 'Audi A6 2.0',
       'Audi A8', 'Audi Q3 2.0', 'Audi Q5 2.0', 'Audi Q7', 'BMW 3 Series',
       'BMW 5 Series', 'BMW 7 Series', 'BMW X1', 'BMW X1 sDrive20d',
       'BMW X1 xDrive20d', 'Chevrolet Beat', 'Chevrolet Beat...
       'Volkswagen Passat Diesel', 'Volkswagen Polo',
       'Volkswagen Polo Comfortline', 'Volkswagen Polo Highline',
       'Volkswagen Polo Highline1.2L', 'Volkswagen Polo Trendline',
       'Volkswagen Vento Comfortline', 'Volkswagen Vento Highline',
       'Volkswagen Vento Konekt', 'Volvo S80 Summum'], dtype=object),
                                                                            array(['Diesel', 'LPG', 'Petrol'], dtype=object)]),
                                                  ['name', 'fuel_type'])])),
                ('randomforestregressor', RandomForestRegressor())])

In [ ]:
y_pred1 = pipe1.predict(x_test)
y_pred2 = pipe2.predict(x_test)

In [ ]:
print(r2_score(y_test, y_pred1))

0.5731311949541246

In [ ]:
print(r2_score(y_test, y_pred2))

0.5502212016536996

In [124]:
dt = {}
s = []
for i  in range(1000):
    x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2, random_state=i)
    lr = LinearRegression()
    pipe = make_pipeline(colmn_trans, lr)
    pipe.fit(x_train, y_train)
    y_pred = pipe.predict(x_test)
    dt[i] = r2_score(y_test, y_pred)
    s.append(r2_score(y_test, y_pred))

In [125]:
# best_state = max(dt, key=dt.get)
# best_score = dt[best_state]

# print("Best Random State:", best_state)
# print("Best R2 Score:", best_score)
# Best Random State: 433
# Best R2 Score: 0.8457059012561223

In [126]:
import numpy as np
np.argmax(s)

np.int64(712)

In [127]:
param_grid = {
    'randomforestregressor__n_estimators': [100, 200],
    'randomforestregressor__max_depth': [None, 10, 20],
    'randomforestregressor__min_samples_split': [2, 5],
    'randomforestregressor__min_samples_leaf': [1, 2],
    'randomforestregressor__max_features': ['sqrt', 'log2']
}

In [128]:
from sklearn.model_selection import GridSearchCV
grid_search = GridSearchCV(estimator=pipe2, param_grid=param_grid, cv=5, n_jobs=-1, verbose=2)
grid_search.fit(x_train, y_train)
print("Best Parameters:", grid_search.best_params_)
print("Best Cross-Validation Score:", grid_search.best_score_)

Fitting 5 folds for each of 48 candidates, totalling 240 fits
Best Parameters: {'randomforestregressor__max_depth': None, 'randomforestregressor__max_features': 'log2', 'randomforestregressor__min_samples_leaf': 1, 'randomforestregressor__min_samples_split': 2, 'randomforestregressor__n_estimators': 200}
Best Cross-Validation Score: 0.47978030319374004

In [129]:

final_pipe = make_pipeline(
    colmn_trans,
    RandomForestRegressor(
        max_depth=None,
        max_features='log2',
        min_samples_leaf=1,
        min_samples_split=2,
        n_estimators=100,
        random_state=42
    )
)

final_pipe.fit(x_train, y_train)

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('onehotencoder',
                                                  OneHotEncoder(categories=[array(['Audi A3 Cabriolet', 'Audi A4 1.8', 'Audi A4 2.0', 'Audi A6 2.0',
       'Audi A8', 'Audi Q3 2.0', 'Audi Q5 2.0', 'Audi Q7', 'BMW 3 Series',
       'BMW 5 Series', 'BMW 7 Series', 'BMW X1', 'BMW X1 sDrive20d',
       'BMW X1 xDrive20d', 'Chevrolet Beat', 'Chevrolet Beat...
       'Volkswagen Polo Comfortline', 'Volkswagen Polo Highline',
       'Volkswagen Polo Highline1.2L', 'Volkswagen Polo Trendline',
       'Volkswagen Vento Comfortline', 'Volkswagen Vento Highline',
       'Volkswagen Vento Konekt', 'Volvo S80 Summum'], dtype=object),
                                                                            array(['Diesel', 'LPG', 'Petrol'], dtype=object)]),
                                                  ['name', 'fuel_type'])])),
                ('randomforestregressor',
                 RandomForestRegressor(max_features='log2', random_state=42))])

In [130]:
new_pred2 = final_pipe.predict(x_test)

In [131]:
print(r2_score(y_test, new_pred2))

0.552501075407427

In [132]:
import pickle

pickle.dump(pipe1, open('car_price.pkl','wb'))

In [133]:
pipe1.predict(pd.DataFrame([["Hyundai Santro Xing",		2007,	45000,	"Petrol"]], columns=['name', 'year', 'kms_driven', 'fuel_type']))

array([49564.65077744])

In [134]:
p = list(car['name'].head(100))
print(p)

['Hyundai Santro Xing', 'Mahindra Jeep CL550', 'Hyundai Grand i10', 'Ford EcoSport Titanium', 'Ford Figo', 'Hyundai Eon', 'Ford EcoSport Ambiente', 'Maruti Suzuki Alto', 'Skoda Fabia Classic', 'Maruti Suzuki Stingray', 'Hyundai Elite i20', 'Mahindra Scorpio SLE', 'Hyundai Santro Xing', 'Mahindra Jeep CL550', 'Audi A8', 'Audi Q7', 'Mahindra Scorpio S10', 'Maruti Suzuki Alto', 'Mahindra Scorpio S10', 'Mahindra Scorpio S10', 'Maruti Suzuki Alto', 'Hyundai i20 Sportz', 'Hyundai i20 Sportz', 'Hyundai i20 Sportz', 'Maruti Suzuki Alto', 'Maruti Suzuki Vitara', 'Maruti Suzuki Alto', 'Mahindra Bolero DI', 'Maruti Suzuki Swift', 'Mahindra Scorpio S10', 'Maruti Suzuki Swift', 'Maruti Suzuki Wagon', 'Maruti Suzuki Wagon', 'Toyota Innova 2.0', 'Renault Lodgy 85', 'Skoda Yeti Ambition', 'Maruti Suzuki Baleno', 'Renault Duster 110', 'Renault Duster 85', 'Honda City 1.5', 'Maruti Suzuki Alto', 'Maruti Suzuki Dzire', 'Honda Amaze', 'Honda Amaze 1.5', 'Honda City', 'Datsun Redi GO', 'Maruti Suzuki SX4', 'Mitsubishi Pajero Sport', 'Mahindra Bolero DI', 'Maruti Suzuki Swift', 'Mahindra Scorpio S10', 'Maruti Suzuki Swift', 'Maruti Suzuki Wagon', 'Maruti Suzuki Wagon', 'Mahindra Scorpio S10', 'Maruti Suzuki Swift', 'Honda City ZX', 'Maruti Suzuki Wagon', 'Ford Figo', 'Hyundai Eon', 'Tata Indigo eCS', 'Ford EcoSport Ambiente', 'Tata Indigo eCS', 'Mahindra Scorpio SLE', 'Volkswagen Polo Highline', 'Skoda Fabia Classic', 'Maruti Suzuki Stingray', 'Chevrolet Spark LS', 'Renault Duster 110PS', 'Honda City', 'Mini Cooper S', 'Datsun Redi GO', 'Skoda Fabia 1.2L', 'Honda Amaze', 'Honda Amaze', 'Renault Duster', 'Mini Cooper S', 'Mahindra Scorpio S4', 'Mahindra Scorpio VLX', 'Mahindra Quanto C8', 'Ford EcoSport', 'Honda Brio', 'Volkswagen Vento Highline', 'Hyundai i20 Magna', 'Toyota Corolla Altis', 'Hyundai Verna Transform', 'Toyota Corolla Altis', 'Honda City 1.5', 'Hyundai Elite i20', 'Skoda Fabia 1.2L', 'BMW 3 Series', 'Maruti Suzuki A', 'Toyota Etios GD', 'Ford Figo Diesel', 'Maruti Suzuki Swift', 'Chevrolet Beat LT', 'BMW 7 Series', 'Mahindra XUV500 W8', 'Hyundai i10 Magna', 'Hyundai Verna Fluidic']

In [135]:
car.columns

Index(['name', 'company', 'year', 'Price', 'kms_driven', 'fuel_type'], dtype='str')